markdown: kramdown
collections:
  pages:
    output: true
    permalink: /:path
  apis:
    base_url: true
    code: true
    docs: true
    name: true
    status_slug: true
    tasks: true
  projects:
    code: true
    name: true
    site: true
    status_slug: true
    tasks: true
    categories: true
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
plugins:
  - jekyll-redirect-from
theme: sibr-jekyll-theme
