markdown: kramdown
collections:
  pages:
    output: true
    permalink: /:path
  apis:
    base_url: true
    code: true
    docs: true
    name: true
    status_slug: true
    tasks: true
  projects:
    code: true
    name: true
    site: true
    status_slug: true
    tasks: true
    categories: true
  hackathon-projects:
    name: true
    site: true
    code: true
    description: true
    awards: true
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme

remote_theme: Society-for-Internet-Blaseball-Research/sibr-jekyll-theme

