backend:
  name: github
  repo: Society-for-Internet-Blaseball-Research/sibr.dev
  branch: main
  site_domain: sibrdev.netlify.app

media_folder: "assets" # Media files will be stored in the repo under images/uploads
public_folder: "/assets" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "apis" # Used in routes, e.g., /admin/collections/blog
    label: "APIs" # Used in the UI
    folder: "_apis" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{name}}.md" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Base URL", name: "base_url", widget: "string"}
      - {label: "Docs Link", name: "docs", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}.md" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "projects" # Used in routes, e.g., /admin/collections/blog
    label: "Projects" # Used in the UI
    folder: "_projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{name}}.md" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Site URL (if applicable)", name: "site", widget: "string", required: false}
      - {label: "Code URL (if applicable)", name: "code", widget: "string", required: false}
      - {label: "Tasks / Project Board (if applicable)", name: "tasks", widget: "string", required: false}
      - {label: "Contributors", name: "contributors", widget: "string", required: false}
      - {label: "Categories", name: "types", widget: "string", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
